
trigger:
- devel

jobs:
- job: 'BioSimSpaceLinux'
  pool:
    vmImage: 'Ubuntu-16.04'

  timeoutInMinutes: 180

  steps:
  - script: |
      cd docker/biosimspace-devel && docker build -f Dockerfile -t biosimspace/biosimspace-devel:latest . && cd -
    displayName: 'Build BioSimSpace'
  - script: |
      cd docker/test-devel && docker build -f Dockerfile -t biosimspace/test-devel:latest . && cd -
    displayName: 'Run BioSimSpace tests'
  - script: |
      cd docker/package-devel && docker build -f Dockerfile -t biosimspace/package-devel:latest . && cd -
    displayName: 'Package BioSimSpace into a binary'
  - script: |
      cd docker/document-devel && docker build -f Dockerfile --build-arg github_token="$github_token" --build-arg github_email="$github_email" . && cd -
    env:
      github_token: $(githubToken)
      github_email: $(githubEmail)
    displayName: 'Build documentation and update website'
  - script: |
      cd docker/deploy-devel && docker build -f Dockerfile --build-arg par_url=$par_url . && cd -
      docker login -u $id -p $pswd
      docker push biosimspace/biosimspace-devel:latest
    env:
      par_url: $(parURL)
      pswd: $(dockerPassword)
      id: $(dockerId)
    displayName: 'Deploy to biosimspace.org and dockerhub'
  - script: |
      cd docker/conda && docker build -f Dockerfile --build-arg anaconda_token=$anaconda_token . && cd -
    env:
      anaconda_token: $(anacondaToken)
    displayName: 'Create Conda package and upload to the Anaconda Cloud'
